APP_PORT = 8800
APP_NAME = "transaction"


DATABASE_NAME = "sword"
DATABASE_USER = "sword"
DATABASE_PASSWORD = "password"
#DATABASE_PORT = "127.0.0.1:3306"
DATABASE_PORT = "db"


#AUTH = "127.0.0.1:8802"
AUTH = "auth:8802"

KEY = "123456789012345678901234"