// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceTwoClient is the client API for ServiceTwo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceTwoClient interface {
	UpdateLastName(ctx context.Context, in *UpdateLastNameRequest, opts ...grpc.CallOption) (*UpdateLastNameResponse, error)
	RollbackTwo(ctx context.Context, in *RollbackTwoRequest, opts ...grpc.CallOption) (*RollbackTwoResponse, error)
}

type serviceTwoClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceTwoClient(cc grpc.ClientConnInterface) ServiceTwoClient {
	return &serviceTwoClient{cc}
}

func (c *serviceTwoClient) UpdateLastName(ctx context.Context, in *UpdateLastNameRequest, opts ...grpc.CallOption) (*UpdateLastNameResponse, error) {
	out := new(UpdateLastNameResponse)
	err := c.cc.Invoke(ctx, "/proto.ServiceTwo/UpdateLastName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceTwoClient) RollbackTwo(ctx context.Context, in *RollbackTwoRequest, opts ...grpc.CallOption) (*RollbackTwoResponse, error) {
	out := new(RollbackTwoResponse)
	err := c.cc.Invoke(ctx, "/proto.ServiceTwo/RollbackTwo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceTwoServer is the server API for ServiceTwo service.
// All implementations must embed UnimplementedServiceTwoServer
// for forward compatibility
type ServiceTwoServer interface {
	UpdateLastName(context.Context, *UpdateLastNameRequest) (*UpdateLastNameResponse, error)
	RollbackTwo(context.Context, *RollbackTwoRequest) (*RollbackTwoResponse, error)
	mustEmbedUnimplementedServiceTwoServer()
}

// UnimplementedServiceTwoServer must be embedded to have forward compatible implementations.
type UnimplementedServiceTwoServer struct {
}

func (UnimplementedServiceTwoServer) UpdateLastName(context.Context, *UpdateLastNameRequest) (*UpdateLastNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLastName not implemented")
}
func (UnimplementedServiceTwoServer) RollbackTwo(context.Context, *RollbackTwoRequest) (*RollbackTwoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RollbackTwo not implemented")
}
func (UnimplementedServiceTwoServer) mustEmbedUnimplementedServiceTwoServer() {}

// UnsafeServiceTwoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceTwoServer will
// result in compilation errors.
type UnsafeServiceTwoServer interface {
	mustEmbedUnimplementedServiceTwoServer()
}

func RegisterServiceTwoServer(s grpc.ServiceRegistrar, srv ServiceTwoServer) {
	s.RegisterService(&ServiceTwo_ServiceDesc, srv)
}

func _ServiceTwo_UpdateLastName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLastNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceTwoServer).UpdateLastName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ServiceTwo/UpdateLastName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceTwoServer).UpdateLastName(ctx, req.(*UpdateLastNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceTwo_RollbackTwo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackTwoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceTwoServer).RollbackTwo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ServiceTwo/RollbackTwo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceTwoServer).RollbackTwo(ctx, req.(*RollbackTwoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceTwo_ServiceDesc is the grpc.ServiceDesc for ServiceTwo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceTwo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ServiceTwo",
	HandlerType: (*ServiceTwoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateLastName",
			Handler:    _ServiceTwo_UpdateLastName_Handler,
		},
		{
			MethodName: "RollbackTwo",
			Handler:    _ServiceTwo_RollbackTwo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service2.proto",
}
